server:
  port: 8090
spring:
  application:
    name: Loan-API
  datasource:
    url: jdbc:db2://localhost:50000/loan_api?useTimezone=true&serverTimezone=UTC
    username: sa
    password: 123
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka