server:
  port: 8090
spring:
  application:
    name: Loan-API
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: ${JDBC_DATASOURCE_URL}
  jpa:
    show-sql: true
    generate-ddl: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka